version: '3.8'
services:
  db:
    container_name: mysql-container
    image: mysql:8.0.39-debian
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./mysql:/var/lib/mysql
    env_file:
      - ./.env.dev
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_DATABASE=${DB_NAME}
    ports:
      - 3306:3306
    networks:
      - my_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "${DB_USERNAME}", "-p${DB_PASS}"]
      timeout: 20s
      retries: 10

  web:
    container_name: django-web
    build:
      context: ./
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    networks:
      - my_network
    volumes:
      - ./:/usr/src/app/
    env_file:
      - ./.env.dev
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy
    links:
      - db

networks:
  my_network:
    driver: bridge