# Generated by Django 5.0.7 on 2024-08-08 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MstpdpaAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=50)),
                ('sequence', models.IntegerField(default=None)),
                ('score', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MstpdpaCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('icon', models.CharField(max_length=50)),
                ('sequence', models.IntegerField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='TnxpdpaSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MstpdpaQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('detials', models.TextField()),
                ('sequence', models.IntegerField(default=None)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdpa.mstpdpacategory')),
            ],
        ),
        migrations.CreateModel(
            name='MstpdpaQuestionAnswerResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.TextField(default=None)),
                ('script_path', models.TextField(default=None)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdpa.mstpdpaanswer')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdpa.mstpdpaquestion')),
            ],
        ),
        migrations.CreateModel(
            name='TnxpdpaResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdpa.mstpdpaanswer')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdpa.mstpdpaquestion')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdpa.tnxpdpasession')),
            ],
        ),
        migrations.CreateModel(
            name='TnxpdpaMeasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measure', models.TextField()),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdpa.tnxpdparesult')),
            ],
        ),
    ]
