# Generated by Django 5.0.7 on 2024-08-27 10:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdpa', '0002_mstpdpaanswer_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tnxpdparesult',
            name='session',
        ),
        migrations.AddField(
            model_name='tnxpdparesult',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
