# Generated by Django 5.0.7 on 2024-08-09 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdpa', '0003_tnxpdparesult_text_measurement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tnxpdparesult',
            name='session',
            field=models.CharField(max_length=256),
        ),
        migrations.DeleteModel(
            name='TnxpdpaSession',
        ),
    ]
