# Generated by Django 5.0.7 on 2024-08-27 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdpa', '0004_tnxpdparesult_script_result'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tnxpdpauser',
            old_name='server_url',
            new_name='ssh_server',
        ),
        migrations.AddField(
            model_name='tnxpdpauser',
            name='ssh_port',
            field=models.IntegerField(default=22),
        ),
    ]
