# Generated by Django 5.0.7 on 2024-09-13 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdpa', '0005_rename_server_url_tnxpdpauser_ssh_server_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mstpdpaanswer',
            options={'verbose_name': 'PDPA Answer', 'verbose_name_plural': 'PDPA Answers'},
        ),
        migrations.AlterModelOptions(
            name='mstpdpacategory',
            options={'verbose_name': 'PDPA Category', 'verbose_name_plural': 'PDPA Categories'},
        ),
        migrations.AlterModelOptions(
            name='mstpdpaquestion',
            options={'verbose_name': 'PDPA Question', 'verbose_name_plural': 'PDPA Questions'},
        ),
        migrations.AlterModelOptions(
            name='mstpdpasubcategory',
            options={'verbose_name': 'PDPA Subcategory', 'verbose_name_plural': 'PDPA Subcategories'},
        ),
        migrations.AlterModelOptions(
            name='tnxpdparesult',
            options={'verbose_name': 'Transaction PDPA Result', 'verbose_name_plural': 'Transaction PDPA Results'},
        ),
        migrations.RemoveField(
            model_name='mstpdpaquestion',
            name='file',
        ),
    ]
