# Generated by Django 5.0.7 on 2024-09-13 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdpa', '0007_mstpdpaquestion_is_request_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='TnxAnswerDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdpa.mstpdpaanswer')),
            ],
        ),
    ]
