# Generated by Django 5.0.7 on 2024-09-13 03:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdpa', '0008_tnxanswerdocument'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TnxAnswerDocument',
            new_name='TnxResultDocument',
        ),
        migrations.AlterField(
            model_name='tnxresultdocument',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdpa.tnxpdparesult'),
        ),
    ]
