# Generated by Django 4.2.8 on 2025-04-09 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_tnxauditlog_options_alter_userprofile_options_and_more'),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDPAAuditReport',
            fields=[
            ],
            options={
                'verbose_name': 'PDPA Audit Report',
                'verbose_name_plural': 'PDPA Audit Reports',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('home.tnxpdparesult',),
        ),
    ]
