# Generated by Django 4.2.8 on 2025-03-30 04:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PdpaAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('answer', models.CharField(max_length=255)),
                ('sequence', models.IntegerField(default=None)),
                ('score', models.IntegerField(blank=True, default=0, null=True)),
                ('result_text', models.TextField(blank=True, null=True)),
                ('script', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'PDPA Answer',
                'verbose_name_plural': 'PDPA Answers',
            },
        ),
        migrations.CreateModel(
            name='PdpaQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('details', models.TextField()),
                ('sequence', models.IntegerField(default=None)),
                ('is_request_file', models.BooleanField(blank=True, default=False, null=True)),
                ('answers', models.ManyToManyField(related_name='questions', to='home.pdpaanswer')),
            ],
            options={
                'verbose_name': 'PDPA Question',
                'verbose_name_plural': 'PDPA Questions',
            },
        ),
        migrations.CreateModel(
            name='TnxPdpaResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_measurement', models.TextField(blank=True, default=None, null=True)),
                ('script_result', models.IntegerField(blank=True, default=None, null=True)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.pdpaanswer')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.pdpaquestion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaction PDPA Result',
                'verbose_name_plural': 'Transaction PDPA Results',
            },
        ),
        migrations.AlterModelOptions(
            name='pdpacategory',
            options={'verbose_name': 'Pdpa Category', 'verbose_name_plural': 'Pdpa Categories'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Pdpa User Info', 'verbose_name_plural': 'Pdpa User Info'},
        ),
        migrations.CreateModel(
            name='TnxResultDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.tnxpdparesult')),
            ],
        ),
        migrations.CreateModel(
            name='PdpaSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('icon', models.CharField(max_length=50)),
                ('sequence', models.IntegerField(default=None)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.pdpacategory')),
            ],
            options={
                'verbose_name': 'PDPA Subcategory',
                'verbose_name_plural': 'PDPA Subcategories',
            },
        ),
        migrations.AddField(
            model_name='pdpaquestion',
            name='sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.pdpasubcategory'),
        ),
    ]
