# Generated by Django 4.2.8 on 2025-03-30 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
        ('home', '0002_pdpaanswer_pdpaquestion_tnxpdparesult_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pdpacategory',
            options={'verbose_name': 'PDPA Category', 'verbose_name_plural': 'PDPA Categories'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'PDPA User Info', 'verbose_name_plural': 'PDPA User Info'},
        ),
        migrations.AddField(
            model_name='userprofile',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='reports.companyprofile'),
        ),
    ]
