# Generated by Django 4.2.8 on 2025-04-09 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
        ('home', '0004_alter_tnxpdparesult_options_tnxauditlog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tnxauditlog',
            options={'verbose_name': 'PDPA Audit Log', 'verbose_name_plural': 'PDPA Audit Logs'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Connect to Server', 'verbose_name_plural': 'Connect to Server'},
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='company',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='reports.companyprofile'),
        ),
    ]
