# Generated by Django 5.0.7 on 2024-08-08 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MstPdpcAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=50)),
                ('sequence', models.IntegerField(default=None)),
                ('score', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MstPdpcCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('icon', models.CharField(max_length=50)),
                ('sequence', models.IntegerField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='TnxPdpcSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MstPdpcQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('detials', models.TextField()),
                ('sequence', models.IntegerField(default=None)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdpc.mstpdpccategory')),
            ],
        ),
        migrations.CreateModel(
            name='MstPdpcQuestionAnswerResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.TextField(default=None)),
                ('script_path', models.TextField(default=None)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdpc.mstpdpcanswer')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdpc.mstpdpcquestion')),
            ],
        ),
        migrations.CreateModel(
            name='TnxPdpcResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdpc.mstpdpcanswer')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdpc.mstpdpcquestion')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdpc.tnxpdpcsession')),
            ],
        ),
        migrations.CreateModel(
            name='TnxPdpcMeasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measure', models.TextField()),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdpc.tnxpdpcresult')),
            ],
        ),
    ]
