# Generated by Django 5.0.7 on 2024-08-08 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdpc', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mstpdpcquestion',
            old_name='detials',
            new_name='details',
        ),
    ]
