# Generated by Django 5.0.7 on 2024-08-08 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdpc', '0002_rename_detials_mstpdpcquestion_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='tnxpdpcresult',
            name='text_measurement',
            field=models.TextField(default=None),
        ),
    ]
